### ISSUE TITLE
is it a `sh` or `lua`?

### ISSUE THREAD

**Issue by HelloRWA** [permaweb/ao-cookbook#136]
While I am reading the docs.

Have confusion about this:

the code type here is `sh`
```sh
  Send({ Target = "process ID", Data = "Hello World!" })
```

some times use:

the code type here is `lua`
```lua
Send({ Target = Morpheus, Data = "Morpheus?" })
```

What we should use then? I am working on translate the docs into Chinese, and at the same time I can optimize the docs in English too ;)

**Comment by TillaTheHun0** [comment]
Thanks @HelloRWA , you're right. Both of these should be `lua`. If you feel up for making them all consistent in a PR, please do! Would be best to do that separate from the translation as that sounds like a big one :) .

Ideally, we push small incremental chunks over time instead of large changes all at once. Thanks again!

**Comment by HelloRWA** [comment]
> Thanks @HelloRWA , you're right. Both of these should be `lua`. If you feel up for making them all consistent in a PR, please do! Would be best to do that separate from the translation as that sounds like a big one :) .
> 
> Ideally, we push small incremental chunks over time instead of large changes all at once. Thanks again!

Ok, I will seperate that PR into seperate small PR then.

**Comment by TillaTheHun0** [comment]
Done in #165
